# -*- coding: utf-8 -*-
"""AL Lab Python.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJFvvYpeXuptORrK0vKVQ2ehj-ZTywvO
"""

print("Welcome to the AI Lab!")

name = input
("Enter student name:")
roll = input ("Enter roll number:")
branch = input ("Enter branch:")
print(f"Student {name} with roll number {roll} is from the {branch} branch." )

a = float(input("Enter first number: "))
b = float(input("Enter second number: "))

print("Sum:", a + b)
print("Difference:", a - b)
print("Product:", a * b)

if b != 0:
    print("Quotient:", a / b)
else:
    print("Quotient: Cannot divide by zero!")

celsius = float(input("Enter temperature in Celsius: "))

fahrenheit = (9/5) * celsius + 32

print("Temperature in Fahrenheit:", fahrenheit)

num = int(input("Enter a number: "))

if num % 2 == 0:
    print(num, "is Even")
else:
    print(num, "is Odd")

a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
c = float(input("Enter third number: "))

if a >= b and a >= c:
    print("Largest number is:", a)
elif b >= a and b >= c:
    print("Largest number is:", b)
else:
    print("Largest number is:", c)

N = int(input("Enter the value of N: "))

for i in range(1, N + 1):
    print(i)

N = int(input("Enter a number: "))

fact = 1

for i in range(1, N + 1):
    fact *= i   # same as fact = fact * i

print("Factorial of", N, "is", fact)

numbers = []

print("Enter 5 numbers:")
for i in range(5):
    num = float(input(f"Number {i+1}: "))
    numbers.append(num)

print("List =", numbers)
print("Smallest number =", min(numbers))
print("Largest number =", max(numbers))
2

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

num = int(input("Enter a number: "))

if is_prime(num):
    print(num, "is a Prime Number")
else:
    print(num, "is NOT a Prime Number")