# -*- coding: utf-8 -*-
"""AI Lab-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JmUyN__8f7M8nVavq2LoopocozZRYgEq
"""

a = 10
b = 3.14
c = "Hello, Python!"
d = True
e = [1, 2, 3]
f = (4, 5, 6)
g = {"name": "Sajid"}

print("Values of variables:")
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

print("\nTypes of variables:")
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))

del c

print("\nVariables after deleting 'c':")
print(a, b, d, e, f, g)

num = int(input("Enter a 3-digit number: "))

hundreds = num // 100
tens = (num // 10) % 10
ones = num % 10

reverse_num = (ones * 100) + (tens * 10) + hundreds

print("Reverse of the number is:", reverse_num)

first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")

full_name = last_name + " " + first_name

print("Combined Name:", full_name)

a = 25
b = 10

print("Value of a:", a)
print("Value of b:", b)

print("Memory location of a:", id(a))
print("Memory location of b:", id(b))

print("Does 'a' and 'b' have same memory location?", id(a) == id(b))

float_div = a / b
print("Floating point division (a / b):", float_div)

int_div = a // b
print("Integer division (a // b):", int_div)

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

biggest = (a + b + abs(a - b)) // 2

print("The bigger number is:", biggest)

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

a = a + b
b = a - b
a = a - b

print("After swapping:")
print("a =", a)
print("b =", b)

my_set = {10, 20, 30, 40, 50}

element = int(input("Enter an element to check: "))

if element in my_set:
    print("Element", element, "is PRESENT in the set.")
else:
    print("Element", element, "is NOT PRESENT in the set.")

a = int(input("Enter value of a: "))
b = int(input("Enter value of b: "))
c = int(input("Enter value of c: "))

# a + b > c  AND  a + c > b  AND  b + c > a
result = int((a + b > c) and (a + c > b) and (b + c > a))

print("Output:", result)

x1 = float(input("Enter x1: "))
y1 = float(input("Enter y1: "))
x2 = float(input("Enter x2: "))
y2 = float(input("Enter y2: "))

dx = x2 - x1
dy = y2 - y1

distance = (dx*dx + dy*dy) ** 0.5

print("Distance between the points =", distance)

num = int(input("Enter a 3-digit number: "))

a = num // 100
b = (num // 10) % 10
c = num % 10

if a == c:
    print("It is a palindrome number")
else:
    print("It is not a palindrome number")

ch = input("Enter an alphabet: ")

if 'a' <= ch <= 'z':
    ch = chr(ord(ch) - 32)
elif 'A' <= ch <= 'Z':
    ch = chr(ord(ch) + 32)

print("Opposite case:", ch)

n = int(input("Enter number of terms: "))

a, b = 0, 1

print("Fibonacci Series:")

for i in range(n):
    print(a, end=" ")
    a, b = b, a + b

num = int(input("Enter a number: "))

n = num
prime_factors = []

i = 2
while i * i <= n:
    if n % i == 0:
        prime_factors.append(i)
        while n % i == 0:
            n //= i
    i += 1

if n > 1:
    prime_factors.append(n)

print("Distinct prime factors of", num, "are:", prime_factors)

num = int(input("Enter a number: "))
n = num

print("Distinct Prime Factors are:", end=" ")

i = 2
distinct_factors = set()

while i * i <= n:
    while n % i == 0:
        distinct_factors.add(i)
        n //= i
    i += 1

if n > 1:
    distinct_factors.add(n)

print(", ".join(str(x) for x in sorted(distinct_factors)))

num = int(input("Enter a decimal number: "))

print("1) Binary")
print("2) Octal")
print("3) Hexadecimal")

choice = int(input("Enter your choice: "))

match choice:
    case 1:
        print("Binary:", bin(num)[2:])
    case 2:
        print("Octal:", oct(num)[2:])
    case 3:
        print("Hexadecimal:", hex(num)[2:].upper())
    case _:
        print("Invalid Choice")

import random

secret_number = random.randint(1, 100)

print("Guess the number between 1 and 100!")

while True:
    guess = int(input("Enter your guess: "))

    if guess < secret_number:
        print("Too low! Try again.")
    elif guess > secret_number:
        print("Too high! Try again.")
    else:
        print("Congratulations! You guessed it right!")
        break

rows = int(input("Enter number of rows: "))

for i in range(1, rows + 1):
    for j in range(rows - i):
        print(" ", end="")

    for k in range(2 * i - 1):
        print("*", end="")

    print()